// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKY3mz855lQ-iS91eovhRwOsfBTVQgDQU',
    appId: '1:926012176148:web:6e9d19c65bd8a100edf401',
    messagingSenderId: '926012176148',
    projectId: 'pdm-recibos-22051517',
    authDomain: 'pdm-recibos-22051517.firebaseapp.com',
    storageBucket: 'pdm-recibos-22051517.appspot.com',
    measurementId: 'G-RGPE73BCT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABu3FJfzbLN6Uj9UDvpVvYwQWFmug0f6M',
    appId: '1:926012176148:android:113303083d71e7ceedf401',
    messagingSenderId: '926012176148',
    projectId: 'pdm-recibos-22051517',
    storageBucket: 'pdm-recibos-22051517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOuZBrZ4W7HrFn6Z4mjsDVJWBkOFBreoM',
    appId: '1:926012176148:ios:9d7610f0bd75832dedf401',
    messagingSenderId: '926012176148',
    projectId: 'pdm-recibos-22051517',
    storageBucket: 'pdm-recibos-22051517.appspot.com',
    iosClientId: '926012176148-1101sro6ntc31ftn7g5dndrqh59vp0o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.recibos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOuZBrZ4W7HrFn6Z4mjsDVJWBkOFBreoM',
    appId: '1:926012176148:ios:9d7610f0bd75832dedf401',
    messagingSenderId: '926012176148',
    projectId: 'pdm-recibos-22051517',
    storageBucket: 'pdm-recibos-22051517.appspot.com',
    iosClientId: '926012176148-1101sro6ntc31ftn7g5dndrqh59vp0o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.recibos',
  );
}
